name: flutter_animated_circle
description: "A production-ready Flutter package for creating beautiful, customizable animated circular widgets. Features smooth animations, multi-segment support, scroll-triggered animations, and extensive customization options. Perfect for progress indicators, pie charts, data visualization, and engaging UI elements."

version: 0.0.2

homepage: https://github.com/geridev12/flutter_animated_circle.git

repository: https://github.com/geridev12/flutter_animated_circle.git

issue_tracker: https://github.com/geridev12/flutter_animated_circle/issues

topics:
  - animation
  - circle
  - progress
  - custom-painter

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
